# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWalletTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amt', models.IntegerField()),
                ('transaction_type', models.IntegerField()),
                ('balance_amt', models.PositiveIntegerField(default=0)),
                ('to_user', models.IntegerField()),
                ('to_user_type', models.IntegerField(default=3)),
                ('from_user', models.IntegerField()),
                ('from_user_type', models.IntegerField(default=3)),
            ],
        ),
    ]
