# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWalletUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('passward', models.CharField(max_length=50)),
                ('balance_amt', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
