# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet_biller', '0002_auto_20171120_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywalletbiller',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
